import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang='en'>
            <body className={inter.className}>
                <nav className='flex gap-2 p-4'>
                    <a href='/' className='border p-1 rounded'>
                        Line Chart
                    </a>
                </nav>

                <main className='grid gap-2 p-2 content-center justify-items-center h-[100vh]'>
                    {children}
                </main>
            </body>
        </html>
    );
}
